config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'cheat_sheet', to: 'cheat_sheet#show'
  get 'contribute', to: 'cheat_sheet#contribute'
  get 'about', to: 'cheat_sheet#about'
  get 'privacy_policy', to: 'pages#privacy_policy'
  get '/', to: 'plastic_calculator#calculator'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fact.rb
class Fact < ApplicationRecord
end

app/models/plastic_item.rb
class PlasticItem < ApplicationRecord
  belongs_to :waste_group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/waste_group.rb
class WasteGroup < ApplicationRecord
  has_many :plastic_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cheat_sheet_controller.rb
class CheatSheetController < ApplicationController
  def show
    @facts = Fact.all
  end

  def random_fact
    ids = Fact.pluck(:id)
    Fact.find(ids.sample)
  end

  def contribute
  end

  def about
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def privacy_policy
  end
end

app/controllers/plastic_calculator_controller.rb
class PlasticCalculatorController < ApplicationController
  def random_fact
    ids = Fact.pluck(:id)
    Fact.find(ids.sample)
  end
  
  def calculator
    @fact = random_fact

    items_dictionary = PlasticItem.all.map{ |item|
      {
        :id => item.id, 
        :name => item.name,
        :recyclable => item.recyclable, 
        :description => item.description,
        :plastic_type => item.plastic_type,
        :default_calc_mode => item.default_calc_mode,
        :waste_group_name => item.waste_group.name,
        :weight_gram => item.weight_gram
      }
    }

    @calculator_props = {
      item_types_json: items_dictionary.to_json, 
      intervals_json: ['weekly', 'monthly'].to_json,
      groups_json: WasteGroup.all.to_json
    }

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_class?(test_path)
    return 'active' if request.path == test_path
    ''
  end
end

app/helpers/cheat_sheet_helper.rb
module CheatSheetHelper
end

app/helpers/plastic_calculator_helper.rb
module PlasticCalculatorHelper
end

app/views/cheat_sheet/_random_fact.html.erb
<div class="container cheet-sheet">
  <div class="fact row-fluid" >
    <div class="cs-small-title"> Random Fact from Plastic Cheet Sheet </div>
    <h3><%= @fact.title %></h3>
    <div class="fact-content">
        <%= @fact.description.html_safe %>
        
        <div class='cs-link-fact'>
          <%= link_to "Cheat Sheet", cheat_sheet_path  %>
        </div>
    </div>
  </div>
</div>

app/views/cheat_sheet/about.html.haml
%div
  .container
    %h3  Mission
    
    %p 
      :markdown
        Making **sustainable** decisions is one of the most important things we need to learn as individuals, organisations and all together. What you buy, what you eat, how you travel, what you do and not do will have an impact on the large picture. We need to understand what are the consequences of each our decision, address this in our economy, regulations and culture. 
        To achieve this goal, we need to learn and measure our decisions, then explore alternatives. 

    %p.pt-4 
      %h5.text-center Myfootprint.world is a platform that aims to help us to optimise the consequences of our consumption and waste. 
      %h5.text-center We want to measure people footprint and reward sustainable decisions working with partners across the globe. 

    %p.pt-4 
      %h5 MyFootprint.world goal is to:
      %ul
        %li show people how significant impact their daily life has on our planet
        %li educate them about the nature of the problem
        %li show them what they can do to make a change
        %li connect to people who are role models in movement
        %li help companies to become more sustainable

    %p 
      %h5 Areas of personal footprint we are looking to explore:
      %ul
        %li plastic, packaging, everyday use items 
        %li food 
        %li energy & trantsport 
       
    %p We want to work with everyone to make this as most meaningful and impactful as possible. 

app/views/cheat_sheet/contribute.html.erb
<div class="container cheat-sheet">
  <h2>Looking for contributors</h2>

  <p>
    We are looking for contrubutors that will help us with development of initiative and application. 
    <hr />
    <h5>Business opportunities: </h5>
    <ul>
      <li>Business development</li>
      <li>Project Owner / Manager</li>
    </ul>
    <h5>Technical opportunities:</h5>
    <ul>
      <li>UI/UX designer</li>
      <li>Full stack developer ( Ruby on Rails & React )</li>
    </ul>
    <h5>Other:</h5>
    <ul>
      <li>Researcher</li>
    </ul>
  </p>

  <h3>Roadmap</h3>
  <p>
    <ul>
      <li>Reporting for Plastic Waste Calculator</li>
      <li>Advanced Reporting for Plastic Waste Calculator</li>
      <li>Social Media Share</li>
      <li>Improve Cheet Sheet for Plastic ( Knowledgbase )</li>
      <li>Guides - what you can do to reduce waste.</li>
      <li>Community - linkint to influencrs, actyvists and stories.</li>
      <li>Photo gallery.</li>
    </ul>
  </p>

  <h3>How to apply?</h3>
  Contact us via <a href="https://www.facebook.com/Voyager-Foundation" >Facebook <i class="fab fa-facebook"></i></a>

</div>

app/views/cheat_sheet/show.html.erb
  <div class="container cheat-sheet">

  <div class="row">
    <div class="col-md-12">
        <h1>Plastic Cheat Sheet</h1>
    </div>
  </div>
  <div class="row">
      <div class="col-md-12">
          <div class="accordion" id="accordionExample">
              <% @facts.each do |fact| %> 
              <%
                collapsed_link = "collapsed"
                collapsed_block_style = ""
                if fact.id == @facts.first.id
                  collapsed_link = ""
                  collapsed_block_style = "show"
                end
              %>
                <div class="card">
                  <div class="card-header" id="heading<%= fact.id %>">
                    <h5 class="mb-0">
                      <button class="btn btn-link <%= collapsed_link%>" type="button" data-toggle="collapse"  data-target="#collapse<%= fact.id %>" aria-expanded="false" aria-controls="collapse<%= fact.id %>">
                          <%= fact.title %>
                      </button>
                    </h5>
                  </div>
                  <div id="collapse<%= fact.id %>" class="collapse <%= collapsed_block_style %>" aria-labelledby="heading<%= fact.id %>" data-parent="#accordionExample">
                    <div class="card-body">
                        <%= fact.description.html_safe %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFootprint</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Hotjar Tracking Code for https://myfootprint.world -->
      <script>
          (function(h,o,t,j,a,r){
              h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
              h._hjSettings={hjid:1017674,hjsv:6};
              a=o.getElementsByTagName('head')[0];
              r=o.createElement('script');r.async=1;
              r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
              a.appendChild(r);
          })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
      </script>
      <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-125952608-1"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-125952608-1');
      </script>

  </head>

  <body>
    
    <%= render "shared/navbar" %>    
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="notice"><%= alert %></p>
    <% end %>

    <div class="alert alert-info text-center alert-dismissible fade show" role="alert">
        Application is still <strong>in intensive development</strong> ( WIP ). If you want to help us visit this <%= link_to "page", "contribute" %>. 
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
    </div>

    <%= yield %>

    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/privacy_policy.html.haml
%div
  .container
    :markdown
      # Privacy Policy
      VoyagerFoundation built the MyFootprint.world app as a open source app. This SERVICE is provided by VoyagerFoundation and MyFootprint.world at no cost and is intended
      for use as is.
    
      This page is used to inform website visitors regarding our policies with the collection, use, and
      disclosure of Personal Information if anyone decided to use our Service.
      
      If you choose to use our Service, then you agree to the collection and use of information in
      relation with this policy. The Personal Information that We collect are used for providing and
      improving the Service. We will not use or share your information with anyone except as described
      in this Privacy Policy.
      
      The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions,
      which is accessible at MyFootprint.world, unless otherwise defined in this Privacy Policy.

      ### Information Collection and Use
      
      For a better experience while using our Service, We may require you to provide us with certain personally identifiable information, including but not limited to [add whatever else you collect here, e.g. users name, address, location, pictures. 
      The information that We request is [retained on your device and is not
      collected by us in any way]|[will be retained by us and used as described in this privacy policy.We
      
      The app does use third party services that may collect information used to identify you. [You can mention Google services here and link to Google's privacy policy if you want].

      ### Log Data
      
      We want to inform you that whenever you use our Service, in case of an error in the app We collect
      data and information (through third party products) on your phone called Log Data. This Log Data
      may include information such as your devices’s Internet Protocol (“IP”) address, device name,
      operating system version, configuration of the app when utilising our Service, the time and date
      of your use of the Service, and other statistics.

      ### Cookies
      
      Cookies are files with small amount of data that is commonly used an anonymous unique identifier.
      These are sent to your browser from the website that you visit and are stored on your devices’s
      internal memory.
      This Services does not uses these “cookies” explicitly. However, the app may use third party code
      and libraries that use “cookies” to collection information and to improve their services. You
      have the option to either accept or refuse these cookies, and know when a cookie is being sen
      to your device. If you choose to refuse our cookies, you may not be able to use some portions of
      this Service.

      ### Service Providers
      
      We may employ third-party companies and individuals due to the following reasons:

      - To facilitate our Service;
      - To provide the Service on our behalf;
      - To perform Service-related services; or
      - To assist us in analyzing how our Service is used.
      
      We want to inform users of this Service that these third parties have access to your Personal
      Information. The reason is to perform the tasks assigned to them on our behalf. However, they
      are obligated not to disclose or use the information for any other purpose.

      ### Security

      We value your trust in providing us your Personal Information, thus we are striving to use
      commercially acceptable means of protecting it. But remember that no method of transmission over
      the internet, or method of electronic storage is 100% secure and reliable, and We cannot
      guarantee its absolute security.

      ### Links to Other Sites
      This Service may contain links to other sites. If you click on a third-party link, you will be
      directed to that site. Note that these external sites are not operated by us. Therefore, I
      strongly advise you to review the Privacy Policy of these websites. I have no control over, and
      assume no responsibility for the content, privacy policies, or practices of any third-party
      sites or services.

      ### Children’s Privacy
      This Services do not address anyone under the age of 13. We do not knowingly collect personal
      identifiable information from children under 13. In the case We discover that a child under 13
      has provided us with personal information, We immediately delete this from our servers. If you
      are a parent or guardian and you are aware that your child has provided us with personal
      information, please contact us so that We will be able to do necessary actions.

      ### Changes to This Privacy Policy
      We may update our Privacy Policy from time to time. Thus, you are advised to review this page
      periodically for any changes. We will notify you of any changes by posting the new Privacy Policy
      on this page. These changes are effective immediately, after they are posted on this page.

      ###Contact Us
      If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact
      us.
       
      

app/views/plastic_calculator/calculator.html.erb
<script type="text/javascript">
  $(window).on('load',function(){
      $('#exampleModalCenter').modal('show');
  });
</script>

<%= react_component("CalculatorApp", props: @calculator_props, prerender: false) %>

app/views/shared/_footer.html.erb
<nav class="navbar fixed-bottom navbar-dark bg-dark navbar-brand font-weight-light text-center m-0 footer">
  <a href="https://voyagerfoundation.org">
    © 2018 Copyright: VoyagerFoundation.org
  </a>
</nav>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">MyFootprint</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Calculator", '/', :class => current_class?('/') + ' nav-link' %>
      </li>
      <li class="nav-item">
          <%= link_to "Plastic Cheat Sheet", 'cheat_sheet',  :class => current_class?('/cheat_sheet') + ' nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "About", 'about',  :class => current_class?('/about') + ' nav-link'  %>
    </li>
    <li class="nav-item">
      <%= link_to "Privacy Policy", 'privacy_policy',  :class => current_class?('/privacy_policy') + ' nav-link'  %>
    </li>
    </ul>
    
  </div>
</nav>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>